# Generated by Django 5.2.1 on 2025-06-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Narsalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/')),
                ('original', models.BooleanField()),
                ('asl_narhi', models.IntegerField()),
                ('skid_narhi', models.ImageField(upload_to='')),
                ('tavsifi', models.TextField()),
                ('sharhlar', models.CharField(max_length=500)),
            ],
        ),
    ]
