# Generated by Django 5.2.1 on 2025-07-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_narsalar_skid_narhi'),
    ]

    operations = [
        migrations.AddField(
            model_name='narsalar',
            name='besh',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='narsalar',
            name='bir',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='narsalar',
            name='ikki',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='narsalar',
            name='olti',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='narsalar',
            name='sakkiz',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='narsalar',
            name='tort',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='narsalar',
            name='uch',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='narsalar',
            name='yetti',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
