# Generated by Django 5.2.1 on 2025-07-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='narsalar',
            name='category',
            field=models.CharField(choices=[('elektronika', 'Elektronika'), ('maishiytexnika', 'Maishiy texnika'), ('kiyim', 'Kiyim'), ('poyabzallar', 'Poyabzallar'), ('aksessuarlar', 'Aksessuarlar'), ("go'zallikvaparvarish", "Go'zallik va parvarish"), ('salomatlik', 'Salomatlik'), ("uyro'zg'orbuyumlari", "Uy-ro'zg'or buyumlari"), ("qurilishvata'mirlash", "Qurilish va ta'mirlash")], default='telefon', max_length=20),
        ),
    ]
