# Generated by Django 5.2.1 on 2025-07-31 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_narsalar_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narsalar',
            name='category',
            field=models.CharField(choices=[('elektronika', 'Elektronika'), ('maishiytexnika', 'Maishiy texnika'), ('kiyim', 'Kiyim'), ('poyabzallar', 'Poyabzallar'), ('aksessuarlar', 'Aksessuarlar'), ('gozallikvaparvarish', "Go'zallik va parvarish"), ('salomatlik', 'Salomatlik'), ('uyrozg`orbuyumlari', "Uy-ro'zg'or buyumlari"), ('qurilishvatamirlash', "Qurilish va ta'mirlash")], default='telefon', max_length=20),
        ),
    ]
