# Generated by Django 5.2.4 on 2025-08-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_narsalar_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='narsalar',
            name='nomi',
            field=models.CharField(default='nomalum', max_length=100),
            preserve_default=False,
        ),
    ]
