# Generated by Django 5.2.4 on 2025-08-01 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_narsalar_nomi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='narsalar',
            name='nomi',
        ),
    ]
