# Generated by Django 5.2.4 on 2025-08-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_narsalar_nomi'),
    ]

    operations = [
        migrations.AddField(
            model_name='narsalar',
            name='nasiya_narhi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='narsalar',
            name='nomi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='narsalar',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
