# Generated by Django 5.2.4 on 2025-08-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_narsalar_nasiya_narhi_narsalar_nomi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='narsalar',
            name='boshqa_uslnarx',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
