# Generated by Django 5.2.4 on 2025-08-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_narsalar_boshqa_uslnarx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caruselimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
