# Generated by Django 5.0.4 on 2025-08-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_caruselimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='narsalar',
            name='is_sotilgan',
            field=models.BooleanField(default=False),
        ),
    ]
