# Generated by Django 5.0.4 on 2025-08-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_narsalar_is_sotilgan'),
    ]

    operations = [
        migrations.AddField(
            model_name='narsalar',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
